# Generated by Django 4.2.13 on 2024-08-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
