# Generated by Django 4.2.13 on 2024-09-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='draft', max_length=100),
        ),
    ]
