# Generated by Django 4.2.13 on 2024-09-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
