# Generated by Django 4.2.13 on 2024-09-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_remove_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
