# Generated by Django 4.2.13 on 2024-08-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0011_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirmation_code', models.CharField(max_length=64, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
    ]
