# Generated by Django 4.2.13 on 2024-08-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0012_subscriber_delete_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='confirmation_code',
            field=models.CharField(max_length=50),
        ),
    ]
