# Generated by Django 4.2.13 on 2024-08-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0013_category_category_discription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
